/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MyWeb": {
      "type": "sst.aws.SvelteKit"
    }
    "SB_ANON_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SB_SRV_ROLE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SB_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}